/**
 * One branch -> commit -> PR -> merge cycle.
 *
 * This is the unit of work behind Pull Shark, YOLO and Pair Extraordinaire. A single
 * cycle can satisfy all three at once: a merged PR is Pull Shark, merging it without a
 * review is YOLO, and adding a Co-authored-by trailer makes the same PR count for Pair
 * Extraordinaire too. The orchestrator exploits that rather than running three separate
 * campaigns.
 */

import { mkdirSync, appendFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { gh, git } from '../gh.js';
import { withRetry } from '../throttle.js';

export const LEDGER = join('.gaa', 'ledger.md');

/** Derive a display name from a GitHub noreply address (123+user@users.noreply...). */
export function coauthorName(email) {
  const local = email.split('@')[0] ?? '';
  const plus = local.indexOf('+');
  return plus === -1 ? local : local.slice(plus + 1);
}

export function coauthorTrailer(coauthor) {
  if (!coauthor) return null;
  if (typeof coauthor === 'string') {
    return `Co-authored-by: ${coauthorName(coauthor)} <${coauthor}>`;
  }
  return `Co-authored-by: ${coauthor.name} <${coauthor.email}>`;
}

/**
 * Get back onto an up-to-date default branch. Deliberately uses --ff-only rather than
 * `reset --hard` so that local work is never silently destroyed.
 */
export async function resetToDefault(ctx) {
  const { defaultBranch, root } = ctx;
  const opts = { cwd: root };
  await withRetry(() => git(['fetch', 'origin', defaultBranch], opts));
  await git(['checkout', defaultBranch], opts);
  try {
    await git(['merge', '--ff-only', `origin/${defaultBranch}`], opts);
  } catch (error) {
    throw new Error(
      `Cannot fast-forward ${defaultBranch} to origin/${defaultBranch}. ` +
        `Reconcile your local branch first.\n${error.message}`,
    );
  }
}

/** Confirm git has an identity; commits fail confusingly without one. */
export async function assertGitIdentity(ctx) {
  const opts = { cwd: ctx.root };
  for (const key of ['user.name', 'user.email']) {
    try {
      const value = await git(['config', '--get', key], opts);
      if (!value) throw new Error('empty');
    } catch {
      throw new Error(`git ${key} is not set. Run: git config --global ${key} "..."`);
    }
  }
}

function appendLedger(root, entry) {
  const path = join(root, LEDGER);
  mkdirSync(dirname(path), { recursive: true });
  if (!existsSync(path)) {
    appendFileSync(
      path,
      '# Cycle ledger\n\nOne line per automated pull request.\n\n',
      'utf8',
    );
  }
  appendFileSync(path, `${entry}\n`, 'utf8');
}

/**
 * Run one cycle. Returns { pr, branch }.
 *
 * On failure the working tree is returned to the default branch, but the failed branch
 * is left in place so it can be inspected.
 */
export async function runCycle(ctx, { label, index, coauthor, mergeMethod = 'squash', dryRun }) {
  const { root, defaultBranch } = ctx;
  const opts = { cwd: root };
  const stamp = Date.now().toString(36);
  const branch = `gaa/${label}-${String(index).padStart(4, '0')}-${stamp}`;
  const title = `chore(gaa): ${label} cycle ${index}`;
  const trailer = coauthorTrailer(coauthor);

  if (dryRun) {
    return {
      dryRun: true,
      branch,
      title,
      trailer,
      mergeMethod,
      steps: [
        `git checkout -b ${branch}`,
        `append to ${LEDGER}`,
        `git commit${trailer ? ' (with co-author trailer)' : ''}`,
        `git push -u origin ${branch}`,
        'gh pr create',
        `gh pr merge --${mergeMethod} --delete-branch`,
      ],
    };
  }

  await resetToDefault(ctx);
  await git(['checkout', '-b', branch], opts);

  appendLedger(root, `- ${new Date().toISOString()} · ${label} · cycle ${index} · ${branch}`);

  const message = [
    title,
    '',
    `Automated ${label} cycle generated by get-all-achievements.`,
    ...(trailer ? ['', trailer] : []),
  ].join('\n');

  await git(['add', LEDGER], opts);
  await git(['commit', '-m', message], opts);

  try {
    await withRetry(() => git(['push', '-u', 'origin', branch], opts));

    const prUrl = (
      await withRetry(() =>
        gh(
          [
            'pr',
            'create',
            '--base',
            defaultBranch,
            '--head',
            branch,
            '--title',
            title,
            '--body',
            `Automated \`${label}\` cycle ${index}.`,
          ],
          opts,
        ),
      )
    ).trim();

    const prNumber = Number(prUrl.split('/').pop());

    // No review is requested, which is exactly what earns YOLO.
    await withRetry(() =>
      gh(['pr', 'merge', String(prNumber), `--${mergeMethod}`, '--delete-branch'], opts),
    );

    await resetToDefault(ctx);
    try {
      await git(['branch', '-D', branch], opts);
    } catch {
      // --delete-branch usually removes it already.
    }

    return { branch, prNumber, prUrl, title, trailer, mergeMethod };
  } catch (error) {
    try {
      await git(['checkout', defaultBranch], opts);
    } catch {
      // Leave the tree where it is; the original error matters more.
    }
    throw error;
  }
}
